#Main Data Sheet
```{r}
main_df <- read.csv("C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2021\\Study 2 and 3\\AAADATA\\Bloods Data\\MAIN_DATA_SHEET.csv")
```

```{r}
main_df2 <- read.csv("C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Main_Data_Frame (Outliers_Removed).csv")
```

#Calculating Dilution Factor
```{r}
main_df <- main_df%>%
  #filter(!Sample %in% 22)%>%
  filter(!Sample %in% 235)%>%
  filter(!Sample %in% 236)%>%
  mutate(Dilution_Factor = ((Sample.Volume+Solution)/Sample.Volume))%>%
  mutate(cal_LDH = LDH*Dilution_Factor)%>%
  mutate(cal_CK = CK*Dilution_Factor)%>%
  mutate(cal_Na = (Na-0.68)*Dilution_Factor)%>%
  mutate(cal_K = (K-0.025)*Dilution_Factor)%>%
  mutate(cal_Cl = (Cl-2.8)*Dilution_Factor)%>%
  drop_na(Sample)
main_df$Time_Point <- as.factor(main_df$Time_Point)
  
```

```{r}
main_df2 <- main_df2%>%
  #filter(!Sample %in% 22)%>%
  filter(!Sample %in% 235)%>%
  filter(!Sample %in% 236)%>%
  mutate(Dilution_Factor = ((Sample.Volume+Solution)/Sample.Volume))%>%
  mutate(cal_LDH = LDH*Dilution_Factor)%>%
  mutate(cal_CK = CK*Dilution_Factor)%>%
  mutate(cal_Na = (Na-0.68)*Dilution_Factor)%>%
  mutate(cal_K = (K-0.025)*Dilution_Factor)%>%
  mutate(cal_Cl = (Cl-2.8)*Dilution_Factor)%>%
  drop_na(Sample)
main_df2$Time_Point <- as.factor(main_df2$Time_Point)
  
```

```{r}
boxplot(cal_Cl ~ Session + Time_Point, data = main_df2)
```

```{r}
write.csv(main_df,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Main_Data_Frame (25-08-2022).csv",row.names = FALSE)
```

```{r}
histogram(main_df$cal_Na)
```


#Summary Data
```{r}
BlaSUM <- main_df2%>%
summarySE(measurevar = "Bla", groupvar =c("Session", "Speed", "BFR", "Time_Point", "Participant"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

LDHSUM <- main_df%>%
summarySE(measurevar = "cal_LDH", groupvar =c("Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

CKSUM <- main_df%>%
summarySE(measurevar = "cal_CK", groupvar =c("Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

NaSUM <- main_df%>%
summarySE(measurevar = "cal_Na", groupvar =c("Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

KSUM <- main_df%>%
summarySE(measurevar = "cal_K", groupvar =c("Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

ClSUM <- main_df%>%
summarySE(measurevar = "cal_Cl", groupvar =c("Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)
```

```{r}
write.csv(BlaSUM,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\BLA_sum (02-09-2022).csv",row.names = FALSE)
```


```{r}
main_df_PRE <- main_df%>%
  filter(!Time_Point %in% "2")%>%
  filter(!Time_Point %in% "3")

main_df <- main_df[main_df$cal_Cl <300,]
TRUNK_MAX_X <- TRUNK_MAX_X[TRUNK_MAX_X$TrunkAngle_X <10,]
```

#Calculating Percentage Change
##CK
```{r}
CK_PCHANGE <- main_df2%>%
  summarySE(measurevar = "cal_CK", groupvar =c("Session", "Time_Point","Participant"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)
  
```

```{r}
write.csv(CK_PCHANGE,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\CK_PCHANGE (29-08-2022).csv",row.names = FALSE)
```

```{r}
CK_PCHANGE_CL <- read.csv("C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Percentage Change\\CK_PCHANGE (29-08-2022).csv")
```

```{r}
CK_PCHANGE_CL<-CK_PCHANGE_CL%>%
  mutate(P_CHANGE = ((CK_POST-CK_PRE)/CK_PRE)*100)

CK_PCHANGET2_SUM <-CK_PCHANGE_CL%>% 
summarySE(measurevar = "P_CHANGE", groupvar =c("Time_Point", "BFR", "Speed", "Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

```

##LDH
```{r}
LDH_PCHANGE <- main_df2%>%
  summarySE(measurevar = "cal_LDH", groupvar =c("Session", "Time_Point","Participant"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)
  
```

```{r}
write.csv(LDH_PCHANGE,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\LDH_PCHANGE (29-08-2022).csv",row.names = FALSE)

LDH_PCHANGE_CL <- read.csv("C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Percentage Change\\LDH_PCHANGE (29-08-2022).csv")
```

```{r}
LDH_PCHANGE_CL<-LDH_PCHANGE_CL%>%
  mutate(P_CHANGE = ((LDH_POST-LDH_PRE)/LDH_PRE)*100)

LDH_PCHANGET2_SUM <-LDH_PCHANGE_CL%>% 
summarySE(measurevar = "P_CHANGE", groupvar =c("Time_Point", "BFR", "Speed", "Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

```

##Sodium
```{r}
sodium_PCHANGE <- main_df2%>%
  summarySE(measurevar = "cal_Na", groupvar =c("Session", "Time_Point","Participant"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)
  
```

```{r}
write.csv(sodium_PCHANGE,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\sodium_PCHANGE (12-09-2022a).csv",row.names = FALSE)

sodium_PCHANGE_CL <- read.csv("C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Percentage Change\\sodium_PCHANGE (12-09-2022).csv")
```

```{r}
sodium_PCHANGE_CL<-sodium_PCHANGE_CL%>%
  mutate(P_CHANGE = ((POST_EXERCISE-PRE_EXERCISE)/PRE_EXERCISE)*100)

sodium_PCHANGE_CL_SUM <-sodium_PCHANGE_CL%>% 
summarySE(measurevar = "P_CHANGE", groupvar =c("Time_Point", "BFR", "speed", "Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

```

##Potassium
```{r}
sodium_PCHANGE <- main_df2%>%
  summarySE(measurevar = "cal_K", groupvar =c("Session", "Speed", "BFR", "Time_Point","Participant"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)
  
```

```{r}
write.csv(sodium_PCHANGE,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Percentage Change\\potassium_PCHANGE (12-09-2022).csv",row.names = FALSE)

potassium_PCHANGE_CL <- read.csv("C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Percentage Change\\potassium_PCHANGE (12-09-2022).csv")
```

```{r}
potassium_PCHANGE_CL<-potassium_PCHANGE_CL%>%
  mutate(P_CHANGE = ((POST_EXERCISE-PRE_EXERCISE)/PRE_EXERCISE)*100)

potassium_PCHANGE_CL_SUM <-potassium_PCHANGE_CL%>% 
summarySE(measurevar = "P_CHANGE", groupvar =c("Time_Point", "BFR", "Speed", "Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

```

##Chloride
```{r}
chloride_PCHANGE <- main_df2%>%
  summarySE(measurevar = "cal_Cl", groupvar =c("Session", "Speed", "BFR", "Time_Point","Participant"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)
  
```

```{r}
write.csv(chloride_PCHANGE,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Percentage Change\\chloride_PCHANGE (12-09-2022).csv",row.names = FALSE)

chloride_PCHANGE_CL <- read.csv("C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2022\\Publications\\Study 2 - Bloods\\Percentage Change\\chloride_PCHANGE (12-09-2022).csv")
```

```{r}
chloride_PCHANGE_CL<-chloride_PCHANGE_CL%>%
  mutate(P_CHANGE = ((POST_EXERCISE-PRE_EXERCISE)/PRE_EXERCISE)*100)

chloride_PCHANGE_CL_SUM <-chloride_PCHANGE_CL%>% 
summarySE(measurevar = "P_CHANGE", groupvar =c("Time_Point", "BFR", "Speed", "Session"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)

```




