#Blood Lactate
```{r}
BlaLMM <- lmer(Bla ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed + (1|Participant), data = main_df2)
summary(BlaLMM)
pairwise_Bla <- emmeans(BlaLMM, pairwise ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed, adjust="holm")
pairwise_Bla
```

```{r}
tab_model(BlaLMM)
```

#Creatine Kinase - Percentage Change
```{r}
CKLMM <- lmer(P_CHANGE ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed + (1|Participant), data = CK_PCHANGE_CL)
summary(CKLMM)
pairwiseCK <- emmeans(CKLMM, pairwise ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed, adjust="holm")
pairwiseCK
```
```{r}
tab_model(CKLMM)
```

#Lactate Dehydrogenase
```{r}
LDHLMM <- lmer(P_CHANGE ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed + (1|Participant), data = LDH_PCHANGE_CL)
summary(LDHLMM)
pairwiseLDH <- emmeans(LDHLMM, pairwise ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed, adjust="holm")
pairwiseLDH
```

```{r}
tab_model(LDHLMM)
```

```{r}
names(main_df2)

```
#Total Change
##Sodium
```{r}
NaLMM <- lmer(cal_Na ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed + (1|Participant), data = main_df2)
summary(NaLMM)
pairwise_NaLMM <- emmeans(NaLMM, pairwise ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed, adjust="holm")
pairwise_NaLMM
```

```{r}
tab_model(NaLMM)
```

##Potassium
```{r}
KLMM <- lmer(cal_K ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed + (1|Participant), data = main_df2)
summary(KLMM)
pairwise_KLMM <- emmeans(KLMM, pairwise ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed, adjust="holm")
pairwise_KLMM
```

```{r}
tab_model(KLMM)
```

##Chlorine

```{r}
ClLMM <- lmer(cal_Cl ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed + (1|Participant), data = main_df2)
summary(ClLMM)
pairwise_ClLMM <- emmeans(ClLMM, pairwise ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed, adjust="holm")
pairwise_ClLMM
```

```{r}
tab_model(ClLMM)
```

#Percentage Change
##Sodium
```{r}
NaLMM_PCHANGE <- lmer(P_CHANGE ~ Time_Point + BFR + speed + Time_Point*BFR + Time_Point*speed + (1|Participant), data = sodium_PCHANGE_CL)
summary(NaLMM_PCHANGE)
pairwise_NaLMM_PCHANGE <- emmeans(NaLMM_PCHANGE, pairwise ~ Time_Point + BFR + speed + Time_Point*BFR + Time_Point*speed, adjust="holm")
pairwise_NaLMM_PCHANGE
```

```{r}
tab_model(NaLMM_PCHANGE)
```

##Potassium - Time points taken out currently
```{r}
KLMM_PCHANGE <- lmer(P_CHANGE ~ BFR + Speed + Speed*BFR + (1|Participant), data = potassium_PCHANGE_CL)
summary(KLMM_PCHANGE)
pairwise_KLMM_PCHANGE <- emmeans(KLMM_PCHANGE, pairwise ~ BFR + Speed + Speed*BFR, adjust="holm")
pairwise_KLMM_PCHANGE
```

```{r}
tab_model(KLMM_PCHANGE)
```

##Chloride
```{r}
ClLMM_PCHANGE <- lmer(P_CHANGE ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed + (1|Participant), data = chloride_PCHANGE_CL)
summary(ClLMM_PCHANGE)
pairwise_ClLMM_PCHANGE <- emmeans(ClLMM_PCHANGE, pairwise ~ Time_Point + BFR + Speed + Time_Point*BFR + Time_Point*Speed, adjust="holm")
pairwise_ClLMM_PCHANGE
```

```{r}
tab_model(ClLMM_PCHANGE)
```